### ISSUE TITLE
cap production resque:restart failing, with nothing written to stdout

### ISSUE THREAD

**Issue by zachdaniel** [sshingler/capistrano-resque#97] opened 2015-02-23 20:11 UTC
```
[e6956e94] Command: cd /var/www/html/server/current && bundle exec rake RAILS_ENV=production QUEUE="credential" PIDFILE=/var/www/html/server/shared/tmp/pids/resque_work_1.pid BACKGROUND=yes VERBOSE=1 INTERVAL=5  resque:work >> /dev/null 2>> /dev/null
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@server: rake exit status: 1
rake stdout: Nothing written
rake stderr: Nothing written

SSHKit::Command::Failed: rake exit status: 1
rake stdout: Nothing written
rake stderr: Nothing written

Tasks: TOP => resque:start
(See full trace by running task with --trace)
```

In deploy/production.rb:

```
role :resque_worker, 'server'
role :resque_scheduler, 'server'
set :workers, {:queue => 2}
```

**Comment by mateusdelbianco** [comment] 2015-02-28 20:14
SSHKit::Runner::ExecuteError: Exception while executing as **user@server**: rake exit status: 1

Is your server hostname really 'server'?

**Comment by zachdaniel** [comment] 2015-02-28 23:29
Of course not, I scrubbed all of the details lol.

**Comment by zachdaniel** [comment] 2015-02-28 23:30
We pinpointed the cause of the issue.  It was a misconfiguration in Redis.  That being said, it was near impossible to troubleshoot, and I even with logging level set to :debug we couldn't get anything out of it.

**Comment by mateusdelbianco** [comment] 2015-03-01 03:49
You should set resque_log_file to a path, it's in the README:

https://github.com/sshingler/capistrano-resque#redirecting-output

**Comment by dmarkow** [comment] 2015-03-01 03:50
Closing for now since it appears to be Redis-related, but if @mateusdelbianco's `resque_log_file` config setting still doesn't help reveal the issue, let me know and I'll look into it to see if there's an issue with logging.

**Closed by dmarkow** 2015-03-01 03:50 UTC

**Comment by madnik** [comment] 2015-04-16 06:43
@zachdaniel I'm having the same issue. Do you mind say something about the misconfiguration of redis you had.

**Comment by lucke84** [comment] 2015-04-21 16:12
+1 @madnik  @zachdaniel

**Comment by zachdaniel** [comment] 2015-04-21 21:52
@madnik @lucke84 I would very much like to help, but I've totally forgotten what exactly it was that caused this issue for me, and I don't have access to that code any more.

**Comment by lucke84** [comment] 2015-04-22 07:22
No problem @zachdaniel :)

In my case, I realised there was an issue that prevented the application to start in the first place. I discovered it trying to start the console on the server machine, which failed also telling the cause.
